### ISSUE TITLE
Forward/back buttons too close together for replaying game

### ISSUE THREAD

**Issue by dingbat** [herzbube/littlego#346] opened 2021-01-30 16:24 UTC
Hi, first off, awesome job with this project, I love this app and the fact that it's OSS.

Often times after finishing a game against the AI I like to go back and replay/analyze it move by move. The issue is these buttons are so small and close together, I'm often halfway through the game and accidentally tap on the >| button which means I have to go tap all the way back to where I was.

![IMG_441B8381A46B-1](https://user-images.githubusercontent.com/1389312/106361797-826ec200-62ed-11eb-97b6-0113cbb0f48c.jpeg)

At the very least, I was thinking of spacing them out more, or perhaps even adding a scrubber / slider control too (although I recognize that having the individual forward/back buttons is useful).

Any thoughts on this? I'm happy to work on this once we agree on a solution. Also let me know if there's a way you prefer to track feature requests.

**Comment by herzbube** [comment] 2021-01-31 01:25
Did you realize you can tap on the small blue board position view in the lower-right corner?

Nevertheless, I agree that spacing the buttons out more would be a nice improvement, and it is certainly still within the scope of the next milestone (1.6.0). If you want to try your hand at this it would be an excellent introduction to the project.

I would really love to work with other people on the project, so your collaboration would be very welcome! From looking at your GitHub profile I don't have to tell you anything about pull requests 🙂, so go ahead and fork this repo. The quick-start instructions in `README.Developer` should hopefully get you started, if not then we can work the issues out via email or some other comms channel. A final note: The `develop` branch (which you should base your work on) is currently set to build with Xcode 12.3 and iOS SDK 14.3 - this is not yet reflected in `README.Developer`.

Scrubber/slider: Very good idea! However I see this as a new feature that should be described in a separate issue - go ahead and create a new issue if you like, or I'll do it myself when I get around to it in the next few days. When the issue is there I'll tag it with the "Feature" label, other than that I have no formal routine. I don't think the scrubber/slider feature will fit into 1.6.0 anymore, but let's discuss this in the new issue once it's there.

**Comment by dingbat** [comment] 2021-02-01 06:46
> Did you realize you can tap on the small blue board position view in the lower-right corner?

Interesting! I never knew about that, I was always curious about it. Tapping on that button doesn't seem to do anything on my device (iPhone 8 on iOS 14.4). But I just got the project working on the simulator and I can see that board position UI now, which looks great. Seems like a bug then. I can open an issue and look into it given that I should be able to reliably reproduce it not triggering (assuming you can't).

> I would really love to work with other people on the project, so your collaboration would be very welcome! 

Great! Also, I'm turning on GitHub notifications - been some time since I am back to working on open source and care about them :)

> A final note: The develop branch (which you should base your work on) is currently set to build with Xcode 12.3 and iOS SDK 14.3 - this is not yet reflected in README.Developer.

Yep, so building 3rd party tools failed because of this. Turns out I had Xcode 12.4 & the 14.4 SDK installed, and didn't want to downgrade Xcode/do some hacky things. Luckily the fix was pretty small, and I opened a PR for it, assuming you didn't want to lock it for a particular reason (can discuss there): https://github.com/herzbube/littlego/pull/351

Great documentation, by the way.

> However I see this as a new feature that should be described in a separate issue

Agreed. I agree that it's not urgent also, especially if we can get this issue ironed out. I can add a new issue for it soon unless you beat me to it.

**Comment by herzbube** [comment] 2021-02-01 12:07
> Tapping on that button doesn't seem to do anything on my device (iPhone 8 on iOS 14.4).

Right. I forgot that I found that bug and fixed it already. Apologies. So no need to open an issue, see #344 and the associated commit.

> Great documentation, by the way.

Thanks. I put a lot of effort into it, mostly out of self-interest because I tend to forget things, but of course I always hope that someone else finds it useful, too. It's nice to hear that it does the job.

> I can add a new issue for it soon unless you beat me to it.

Done, it's #353.

BTW: I enabled "Discussions" on this repo, so maybe we can take some of the talk there. I started [this topic](https://github.com/herzbube/littlego/discussions/355) to discuss things related to the upcoming 1.6.0 release, such as whether a slider is in or out of scope.

**Closed** 2021-02-01 21:45 UTC
Labels: change request, prio 1, user feedback
