### ISSUE TITLE
Fuego thinks forever in latest update

### ISSUE THREAD

**Issue by Spurlock** [herzbube/littlego#328] opened 2019-01-16 19:39 UTC
In playing games against the computer, the AI somehow gets stuck "thinking" indefinitely by the second move. This happens even against the "weak" computer player that normally plays almost instantly.

So far I've been unable to get more than 2 moves into any game I've played against the computer since downloading the latest update.

I am running iOS 12.1.1 on an iPhone SE.

**Comment by herzbube** [comment] 2019-01-17 01:17
Thanks for reporting this. This is a combination of two bugs:

1. Fuego for some reason that I'm still investigating is not seeing handicap stones when it generates a move (the `genmove` GTP command). This results in an error status reported back to Little Go. You can see the erroneous GTP command under "Diagnostics > GTP Log".
1. Little Go does not have proper error handling for this scenario. The result of this is that the UI never gets updated although the computer is no longer actually thinking.

I already have a fix for the second problem. The first problem, however, which is the actual root cause, is surprisingly difficult to debug. I'll update the issue as soon as I know more.

**Comment by herzbube** [comment] 2019-01-17 03:30
Found the solution for problem 1. This is a bug in Fuego itself. It's now fixed in the fuego-on-ios project: See [issue 20](https://github.com/herzbube/fuego-on-ios/issues/20). As a precaution, a similar bug was also fixed: See [issue 21](https://github.com/herzbube/fuego-on-ios/issues/20).

**Comment by Spurlock** [comment] 2019-01-17 04:15
Awesome, thanks for the update! 

It sounds like you've got it figured out, but I wanted to clarify just in case that the games I was playing didn't have any handicap stones, so I'm not sure why problem 1 would apply.

**Comment by herzbube** [comment] 2019-01-17 08:34
Yeah, I guess the bug could have affected anyone playing a stone on one of the 4/4 intersections within the first couple of moves. The handicap use case was merely how I could reproduce the problem.

**Closed** 2019-01-19 20:21 UTC
Labels: bug, prio 1
